spring:
  application:
    name: transportation
  datasource:
    url: jdbc:mysql://localhost:3306/busdb?useSSL=false&serverTimezone=UTC
    username: root
    password: Christinaprince@2002
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update  # Consider changing to 'validate' or 'none' in production
    show-sql: true
bus:
  max:
    delay: 15.0

server:
  port: 0

eureka:
  client:
    registerWithEureka: true  # Registers this service with the Eureka server
    fetchRegistry: true       # Fetches the registry from the Eureka server
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/  # URL of the Eureka server to connect with
  instance:
    hostname: localhost  # The hostname of the instance
    instance-id: "${spring.application.name}:${instanceId:${random.value}}"



#spring.application.name=transportation
#
#spring.datasource.url=jdbc:mysql://localhost:3306/busdb
#spring.datasource.username=root
#spring.datasource.password=Christinaprince@2002
#
#spring.jpa.show-sql=true
#
## Uncomment the following lines if needed:
## security.basic.enable=false
## security.ignored=/**
#
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
## spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL55Dialect
#
#
#
#spring.mvc.throw-exception-if-no-handler-found=true
#spring.resources.add-mappings=false
## Maximum delay in minutes
#bus.max.delay=15.0
#
## Server Configuration
#server.port=0
#
## Eureka Client Configuration
#eureka.client.registerWithEureka=true # Registers this service with the Eureka server
##eureka.client.fetchRegistry=true # Fetches the registry from the Eureka server
#eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/ # URL of the Eureka server to connect with
#
## Instance Configuration
#eureka.instance.hostname=localhost # The hostname of the instance
#eureka.instance.instance-id=${spring.application.name}:${instanceId:${random.value}}
#
#
